let goblin_pow=15
let goblin_e=5
let goblin_m=25
function goblin(){
	ev["goblin1"]={
		ev:function(){
			show("你在带薪摸鱼的时候看到了群友分享了一个微信小程序。")
			if (check("str",goblin_pow)>=0) {
				show("你嗤之以鼻。")
				gain({exp:goblin_e,money:goblin_m})
			}else{
				show("你虽然觉得小程序狗都不写，但觉得其或许有可取之处。")
				gain({v_exp:1})
			}
		},
		town:false,
		chance:function(){
			return 1
		},
		end:1
	}
	ev["goblin2"]={
		ev:function(){
			show("你在带薪摸鱼的时候看到了群友分享了一个微信小程序的源代码。")
			if (check("dex",goblin_pow)>=0) {
				show("你发现了这是个陷阱。")
				show("你不动声色地绕开了。")
				gain({exp:goblin_e,money:goblin_m})
			}else{
				show("你踩中了陷阱。")
				if(rand(2)>=1){
					show("领导发现你在看小程序，觉得你也可以自己搞一个。")
					show("现在你不得不加班写小程序了。")
					gain({v_exp:3,e_exp:2},"小程序")
				}
				else{
					show("幸运的是，领导并没发现你在看小程序。")
					show("所以无事发生。")
					gain({p_exp:2})
				}
			}
		},
		town:false,
		chance:function(){
			return 1
		},
		end:1
	}
	ev["goblin3"]={
		ev:function(){
			show("你在带薪摸鱼的时候看到了群友分享了一个微信小程序。")
			show("你嗤之以鼻。")
			gain({exp:goblin_e,money:goblin_m})
			pause()
			if(check("str", goblin_pow+2)>=0){
				show("但这时候领导说甲方也想要个小程序。")
				show("你装作没看见，糊弄了过去。")
				gain({exp:goblin_e,money:goblin_m,b_exp:1})
			}else{
				show("但这时候领导说甲方也想要个小程序。")
				show("你竭尽全力地糊弄过去。")
				gain({b_exp:3})
				if(rand(4)==0){
					show("但没能糊弄过去，你需要整天写小程序了。")
					gainbuff("监禁：小程序",1)
				}else{
					show("你赶在更多小程序出现前润了。")
				}
			}
		},
		town:false,
		chance:function(){
			if(week-chapter_startweek<=3)return 0
			return 1
		},
		end:1
	}
	ev["goblin4"]={
		ev:function(){
			show("你遭遇了一群小程序。",true)
			ans=check("dex",goblin_pow+2)
			if(ans>=7){
				show("你巧妙地把锅甩给了同事们。")
				gain({exp:goblin_e*3,money:goblin_m*3})
			}else if(ans>=0){
				show("你巧妙地让同事分担了你的活。")
				gain({exp:goblin_e,money:goblin_m})
			}else{
				show("小程序轮流袭击你身上的敏感部位，令你手忙脚乱。")
				gain({"v_exp":1,"b_exp":1,"e_exp":1})
				show("你很快就招架不住了。",true)
				if(rand(2)==0){
					show("你只好加班。")
					gain({"v_exp":3,"b_exp":3,"e_exp":3},"小程序")
				}else{
					show("但这时你的同事过来帮你分担了一些活，你乘机润了。")
				}
			}
		},
		town:false,
		chance:function(){
			if(week-chapter_startweek<=3)return 0
			return 1
		},
		end:1
	}
	ev["goblin5"]={
		ev:function(){
			var ans=check("wis",goblin_pow+2)
			if(ans<0){
				var ans2=rand(10)
				show("小程序法师对你释放了一个法术。")
				show("好像什么都没有发生。",true)
				if(ans2<=3){
					show("你正要做出反击时，小程序法师示意你去写一个小程序。")
					show("你的身体不受控制地遵循了它的指示。")
					gain({p_exp:2})
					pause()
					if(ans2<=2){
						show("你被操控着夸赞着小程序。")
						gain({b_exp:3,v_exp:1},"小程序法师")
						pause()
						if(ans2<=1){
							show("在它满足了后，他又命令你加班写小程序。")
							gain({e_exp:2})
							pause()
							if(ans2<=0){
								show("你随着它一直加班。")
								gain({e_exp:5})
								gainbuff("监禁：小程序",1)
								show("你取回了对身体的控制权，但是为时已晚。")
								return
							}
						}
					}
					show("你取回了对身体的控制权，趁它不备润了。")
					return
				}
				show("它示意你靠近。你走上前结果了它。")
				gain({exp:goblin_e,money:goblin_m*2})
			}else{
				show("小程序法师打算对你释放了一个法术，你赶在吟唱完成前结果了它。")
				gain({exp:goblin_e,money:goblin_m*2})
			}
		},
		town:false,
		chance:function(){
			if(week-chapter_startweek<=3)return 0
			return 1
		},
		end:1
	}
	ev["goblin_village2"]={
		ev:function(){
			show("你制定了一个大胆的小程序村讨伐计划。",true)
			show("你假装自己正在加班写小程序。")
			gain({e_exp:3},true)
			show("小程序法师注意到了你。你继续作出沉迷加班无法自拔的样子。")
			if(rand(3)==0){
				show("小程序法师认为你加班很开心，给你安排了更多的小程序。")
				gain({v_exp:3,p_exp:1},true)
				show("你在加班过程中渐渐地忘记了自己原本的目的，顺从地继续加班。",true)
				show("或许这正是你本来的目的？")
				gainbuff("监禁：小程序",1)
			}else{
				show("小程序法师认为你加班很开心，给你安排了更多的小程序。")
				gain({e_exp:3},true)
				show("你乘着小程序法师没有防备，用手里的键盘作为武器攻击了它。",true)
				show("你重复着这样的操作，将小程序法师的战力逐渐消灭。")
				gain({exp:goblin_e*2,money:goblin_m*2})
				show("",true)
				/*if(getop("武道家")<-100){
					show("你救出了被折磨得不成人形的武道家。")
					if(week<=op["武道家"].prison){
						show("武道家拒绝了你的搀扶，挣扎着站了起来。")
						op["武道家"].val+=10000
						gainop("武道家")
						gainbuff("武道家的战友")
					}else{
						show("武道家似乎已经忘了如何直立行走，跟在你后面爬行着。")
						show("",true)
						show("武道家退出了冒险者公会。")
						if("武道家的战友" in buff)
						gainbuff("武道家的战友",-10000)
					}
					pause()
				}*/		
				gain({"money":100})
				chapter=2
				chapter_startweek=week
				pause()
				show("你的冒险者等级提升了。")
			}
		},
		town:false,
		chance:function(){
			if("goblin_aftermath" in past_event)return 1
		},
		end:1
	}
	ev["goblin_village"]={
		ev:function(){
			show("你闯进了小程序村。",true)
			for(i=1;i<=3;i++){
				var r=rand(4)
				if(r==1){
					/*if (check("dex",goblin_pow)>=0) {
						show("你发现了哥布林设下的陷阱。")
						show("你不动声色地绕开了，随后揪出埋伏在一旁的哥布林。")
						gain({exp:goblin_e,money:goblin_m})
					}else{
						show("你踩中了哥布林设下的陷阱。")
						show("埋伏在一旁的哥布林侵犯了你。")
						gain({v_exp:3,p_exp:2,s_exp:1},"哥布林")
						pause()
						show("然后，更多哥布林围了上来。")
						gainbuff("监禁：小程序",1)
						return
					}*/
					if (check("dex",goblin_pow)>=0) {
						show("你发现了小程序设下的陷阱。")
						show("你不动声色地绕开了。")
						gain({exp:goblin_e,money:goblin_m})
					}else{
						show("你踩中了小程序设下的陷阱。")
						show("现在你不得不加班写小程序了。")
						gain({v_exp:3,e_exp:2},"小程序")
						show("然后，更多小程序围了上来。")
						gainbuff("监禁：小程序",1)
						return
					}
				}else if(r==2){
					/*show("你杀死了一个落单的哥布林。")
					gain({exp:goblin_e,money:goblin_m})
					pause()
					if(check("str",goblin_pow+2)>=0){
						show("在你搜刮战利品时，藏在一旁的哥布林从背后抓住了你。")
						show("你在被它揉弄了几下胸部之后才摆脱了哥布林的压制，随后你又多了一份战利品。")
						gain({exp:goblin_e,money:goblin_m,b_exp:1})
					}else{
						show("在你搜刮战利品时，藏在一旁的哥布林从背后抓住了你。")
						show("它抓住你的胸部使劲揉弄。你一时之间浑身酸软，无法反抗。")
						gain({b_exp:3})
						show("更多哥布林冒了出来。你被它们捆得严严实实。")
						gainbuff("监禁：小程序",1)
						return
					}*/
					show("你看到了一个微信小程序。")
					show("你嗤之以鼻。")
					gain({exp:goblin_e,money:goblin_m})
					pause()
					if(check("str", goblin_pow+2)>=0){
						show("但这时候另一个微信小程序抓住了你。")
						show("你摆脱了。")
						gain({exp:goblin_e,money:goblin_m,b_exp:1})
					}else{
						show("但这时候另一个微信小程序抓住了你。")
						show("你没能摆脱，现在你需要整天写小程序了。")
						gainbuff("监禁：小程序",1)
						gain({b_exp:3})
						return
					}
				}else if(r==3){
					/*show("你遭遇了一支哥布林小队。",true)
					ans=check("dex",goblin_pow+2)
					if(ans>=7){
						show("你巧妙地将哥布林小队各个击破。")
						gain({exp:goblin_e*3,money:goblin_m*2*3})
					}else if(ans>=0){
						show("在击倒其中一个哥布林后，你突破了他们的包围。")
						gain({exp:goblin_e,money:goblin_m})
					}else{
						show("它们轮流袭击你身上的敏感部位，令你手忙脚乱。")
						gain({"v_exp":1,"b_exp":1,"a_exp":1})
						show("你很快就招架不住了。",true)
						if(rand(2)==0){
							show("它们分别占据了你身上的一个洞，各自动起了腰。")
							gain({"v_exp":3,"a_exp":3,"o_exp":3,"s_exp":3},"哥布林")
							show("更多哥布林冒了出来。你被它们捆得严严实实。")
							gainbuff("监禁：小程序",1)
							return
						}else{
							show("它们为谁先侵犯你发生了争执。别的哥布林反而抢先享用起你的身体。")
							show("等到新来的哥布林在你的体内射了一发之后，它们的争论还没有结束。")
							gain({"v_exp":3,"s_exp":1},"哥布林")
							gainbuff("监禁：小程序",1)
							return
						}
					}*/
					show("你遭遇了一群小程序。",true)
					ans=check("dex",goblin_pow+2)
					if(ans>=7){
						show("你巧妙地把锅甩给了同事们。")
						gain({exp:goblin_e*3,money:goblin_m*3})
					}else if(ans>=0){
						show("你巧妙地让同事分担了你的活。")
						gain({exp:goblin_e,money:goblin_m})
					}else{
						show("小程序轮流袭击你身上的敏感部位，令你手忙脚乱。")
						gain({"v_exp":1,"b_exp":1,"e_exp":1})
						show("你很快就招架不住了。",true)
						gain({"v_exp":3,"b_exp":3,"e_exp":3},"小程序")
						gainbuff("监禁：小程序",1)
						return
					}
				}else{
					/*var ans=check("wis",goblin_pow+2)
					if(ans<0){
						var ans2=rand(10)
						show("哥布林法师对你释放了一个法术。")
						show("好像什么都没有发生。",true)
						if(ans2<=3){
							show("你正要做出反击时，哥布林法师示意你用狗爬的姿势靠近它。")
							show("你的身体不受控制地遵循了它的指示。")
							gain({p_exp:2})
							pause()
							if(ans2<=2){
								show("你被操控着伸出舌头，舔舐着它的肉棒。")
								gain({o_exp:3,s_exp:1},"哥布林法师")
								pause()
								if(ans2<=1){
									show("在它满足了后，他又命令你脱光衣服，以四肢着地的姿势跟在他身后。")
									gain({e_exp:2})
									pause()
									if(ans2<=0){
										show("你随着它绕着村子爬了一圈。")
										gain({e_exp:5})
										gainbuff("监禁：小程序",1)
										show("你取回了对身体的控制权，但是为时已晚。")
										return
									}
								}
							}
							show("你取回了对身体的控制权，试图从这里脱身。")
							show("围观的哥布林大失所望。")
							show("法师恼怒地指挥它们包围了你。")
							gainbuff("监禁：小程序",1)
							return
						}
						show("它示意你靠近。你走上前结果了它。")
						gain({exp:goblin_e,money:goblin_m*2})
					}else{
						show("哥布林法师打算对你释放了一个法术，你赶在吟唱完成前结果了它。")
						gain({exp:goblin_e,money:goblin_m*2})
					}*/
					var ans=check("wis",goblin_pow+2)
					if(ans<0){
						var ans2=rand(10)
						show("小程序法师对你释放了一个法术。")
						show("好像什么都没有发生。",true)
						if(ans2<=3){
							show("你正要做出反击时，小程序法师示意你去写一个小程序。")
							show("你的身体不受控制地遵循了它的指示。")
							gain({p_exp:2})
							pause()
							if(ans2<=2){
								show("你被操控着夸赞着小程序。")
								gain({b_exp:3,v_exp:1},"小程序法师")
								pause()
								if(ans2<=1){
									show("在它满足了后，他又命令你加班写小程序。")
									gain({e_exp:2})
									pause()
									if(ans2<=0){
										show("你随着它一直加班。")
										gain({e_exp:5})
										gainbuff("监禁：小程序",1)
										show("你取回了对身体的控制权，但是为时已晚。")
										return
									}
								}
							}
							show("你取回了对身体的控制权。")
							show("围观的小程序大失所望。")
							show("法师恼怒地指挥它们包围了你。")
							gainbuff("监禁：小程序",1)
							return
						}
						show("它示意你靠近。你走上前结果了它。")
						gain({exp:goblin_e,money:goblin_m*2})
					}else{
						show("小程序法师打算对你释放了一个法术，你赶在吟唱完成前结果了它。")
						gain({exp:goblin_e,money:goblin_m*2})
					}
				}
				pause()
			}
			/*if(getop("武道家")<-100){
				show("你救出了被折磨得不成人形的武道家。")
				if(week<=op["武道家"].prison){
					show("武道家拒绝了你的搀扶，挣扎着站了起来。")
					op["武道家"].val+=10000
					gainop("武道家")
					gainbuff("武道家的战友")
				}else{
					show("武道家似乎已经忘了如何直立行走，跟在你后面爬行着。")
					show("",true)
					show("武道家退出了冒险者公会。")
					if("武道家的战友" in buff)
						gainbuff("武道家的战友",-10000)
				}
				pause()
			}*/
			show("你在小程序村里大杀特杀，然后放火烧毁了这个地方。",true)
			gain({"money":100})
			//gainbuff("讨伐证明：哥布林村")
			chapter=2
			chapter_startweek=week
			pause()
			show("你的冒险者等级提升了。")
		},
		town:false,
		chance:function(){
			if("讨伐证明：小程序村"in buff){
				return 0
			}
			if(week-chapter_startweek<=7)return 0
			//if(getop("武道家")<-100)return 2
			return 1
		},
		end: 1
	}
	/*ev["goblin_aftermath"]={
		ev:function(){
			show("你遇到了一个眼熟的哥布林。")
			show("你看着它朝你勃起的阴茎，想起了在哥布林村的日子。")
			ans=rand(8)
			if(ans==0){
				show("你下意识地舔了几下它的阴茎，才想起了哥布林是你必须打倒的敌人。",true)
				show("但你有些怀念哥布林精液的味道，一直舔到它射出来为止。")
				gain({o_exp:3,s_exp:1})
				show("",true)
				show("你以狗爬的姿势随着它返回了哥布林村。")
				show("当冰冷的链条再一次栓到你的脖子上时，你才意识到这并不是一场春梦。")
				gainbuff("监禁：小程序",1)
			}else if(ans<=4){
				show("你下意识地舔了几下它的阴茎，才想起了哥布林是你必须打倒的敌人。",true)
				show("但你有些怀念哥布林精液的味道，一直舔到它射出来为止。")
				gain({o_exp:3,s_exp:1})
			}else{
				show("你下意识地舔了几下它的阴茎，才想起了哥布林是你必须打倒的敌人。")
				gain({exp:goblin_e,money:goblin_m,o_exp:1})
			}
		},
		town:false,
		chance:function(){
			if(past_event.includes("goblin_prison2")){
				return 1
			}
		},
		end:1
	}*/
	ev["goblin_prison1"]={
		ev:function(){
			show("你没日没夜地加班写小程序。")
			if(buff["监禁：小程序"]<=2)
				show("你只能屈辱地加班。")
			else{
				show("你渐渐地习惯了。")
				show("你会自觉地加班写小程序。")
			}
			gain({v_exp:5,b_exp:5,e_exp:5,p_exp:5},"小程序")
			if(buff["监禁：小程序"]==1 && past_event.includes("goblin_prison1")){
				pause()
				show("由于这不是你第一次被监禁写小程序，你适应得很快。")
				gainbuff("监禁：小程序",1)
			}
			/*if(op["武道家"]!=null&&op["武道家"].val<0){
				show("",true)
				if(week<=op["武道家"].prison){
					show("武道家被拴在你的旁边。")
					show("你时不时能听到她高亢的骂声。")
				}else{
					show("武道家被拴在你的旁边。")
					show("你时不时能听到她高亢的叫床声。")
				}
			}*/
		},
		town:true,
		chance:function(){
			if("监禁：小程序"in buff){
				return 100000
			}
		}
	}
	ev["goblin_prison2"]={
		ev:function(){
			ans=rand(4)
			//if((ans==0)&&op["武道家"]==null)ans=2
			if(buff["监禁：小程序"]>=4 && rand(5)<buff["监禁：小程序"]-3)ans=2
			if(ans==0){
				/*if(op["武道家"]!=null){
					if(op["武道家"].val<0){
						show("哥布林村的村长想要试一试双人侍奉的滋味，命令武道家和你一起为它服务。")
						show("你们的舌头在舔舐时不时会触碰到对方。")
						show("与其说你们在双人口交，不如说你们在隔着一根哥布林肉棒接吻。")
						gain({"o_exp":3,"s_exp":1,"les_exp":1})
						gainbuff("监禁：小程序",1)
					}else{
						show("武道家闯入了哥布林村。",true)
						if(rand(2)==1){
							show("她被哥布林法师的催眠魔法命中，脱光衣服摆出四肢着地的姿势，然后被哥布林干得高潮连连。")
							show("等到她被锁链拴住后，她才恢复意识，还困惑地问你刚才发生了什么。")
							show("你无言以对。")
							op["武道家"].val-=10000
							op["武道家"].prison=week+5
							gainbuff("监禁：小程序",1)
						}else{
							show("她掏出一把匕首斩断了锁链，带着你逃了出去。")
							gainbuff("监禁：小程序",-10000)
							show("",true)
							show("事后你请她到城里最好的餐馆大吃了一顿。")
							gain({money:-60})
						}
					}
				}else{
					ans=2
				}*/
				ans = 2
			}else if(ans==1){
				show("小程序法师以你为教具，向学徒传授怎么写小程序。",true)
				if(rand(4)==0){
					show("魔法生效了。")
					show("你像狗一样写着小程序。")
					gain({e_exp:2})
				}else if(buff["监禁：小程序"]>2){
					show("魔法失效了。")
					show("你见到法师有些生气，连忙假装魔法生效了。")
					show("你像狗一样写着小程序。")
					gain({e_exp:2})
				}else{
					show("魔法失效了。")
					show("小程序法师见你没有反应，生气地用它的法杖击打你的屁股。")
					gain({p_exp:3})
				}
				gainbuff("监禁：小程序",1)
			}else if(ans==2){
				if(buff["监禁：小程序"]<=2){
					/*if(op["武道家"]!=null&&op["武道家"].val<0){
						if(week<=op["武道家"].prison)
							show("你和武道家低声商量着逃跑计划，直到被哥布林的肉棒打断。")
						else
							show("你试图和武道家交谈，但她沉迷于哥布林的肉棒，没有理你。")
					}
					else*/
						show("你默默地忍受着写小程序，等待着逃跑的时机。")
					gain({v_exp:3},"小程序")
					gainbuff("监禁：小程序",1)

				}else{
					show("你放弃了抵抗。")
					show("你会主动写小程序。",true)
					show("你会主动加班写小程序。")
					show("你主动写着小程序，以小程序的狗的身份成为了村子的成员。",true)
					show("")
					show("结局：小程序的狗")
					gameover=true
				}
			}else{
				show("负责看守的小程序睡着了，你注意到钥匙从它的怀中掉了出来。",true)
				show("你设法用足尖勾到了钥匙，然后解开了锁链。")
				gain({v_exp:3},"小程序")
				/*if(op["武道家"]!=null&&op["武道家"].val<0){
					show("你为武道家打开了锁。")
					if(week>op["武道家"].prison){
						show("武道家似乎已经忘了如何直立行走，你只能独自逃出去。")
					}
				}*/
				if(check("dex",goblin_pow-buff["监禁：小程序"])>=0){
					/*if(op["武道家"]!=null&&op["武道家"].val<0&&week<=op["武道家"].prison){
						show("你和武道家相互支持着逃了出去。")
						op["武道家"].val+=10000
						gainbuff("监禁：小程序",-10000)
						gainop("武道家")
						gainbuff("武道家的战友")
					}else{
						show("你逃了出去。")
						gainbuff("监禁：小程序",-10000)
					}*/
					show("你逃了出去。")
					gainbuff("监禁：小程序",-10000)
				}else{
					/*if(op["武道家"]!=null&&op["武道家"].val<0&&week<=op["武道家"].prison){
						show("在逃跑途中你们被哥布林发现了。")
						show("武道家当机立断地迎上去舔舐哥布林的肉棒。哥布林以为只是一条母狗没拴好，没有意识到逃跑的母狗不止一条。")
						show("你乘机逃了出来。")
						gainbuff("监禁：小程序",-10000)
					}else{
				
						show("在逃跑途中你被哥布林发现了。")
						if(buff["监禁：小程序"]<=2){
							show("作为惩罚，你接受了大量的凌辱。")
							gain({v_exp:10,a_exp:10,o_exp:5,b_exp:5,e_exp:5,s_exp:10,p_exp:20},"哥布林")
						}else{
							show("你当机立断地迎上去舔舐哥布林的肉棒。哥布林以为只是一条母狗没拴好，没有意识到你试图逃跑。")
							gain({b_exp:3,o_exp:5,s_exp:2},"哥布林")
						}
						gainbuff("监禁：小程序",1)
					}*/
					if(buff["监禁：小程序"]<=2){
						show("作为惩罚，你接受了大量的凌辱。")
						gain({v_exp:10,b_exp:5,e_exp:5,p_exp:20},"小程序")
					}else{
						show("你当机立断地加班。小程序以为只是一条狗没拴好，没有意识到你试图逃跑。")
						gain({b_exp:3,e_exp:5,s_exp:2},"小程序")
					}
					gainbuff("监禁：小程序",1)
				}
			}
		},
		town:false,
		chance:function(){
			if("监禁：小程序"in buff){
				return 100000
			}
		}
	}
}